const childProcess = require("child_process");
const fs = require("fs");
const os = require("os");
const path = require("path");
const { LarkIdentity } = require("../../models/larkIdentity");
const { EventLogs } = require("../../models/eventLogs");
const { EncryptionManager } = require("../EncryptionManager");
const { getFreshAccessToken } = require("./oauth");
const { loadLarkConfig } = require("./settings");
const { extractText } = require("./fileText");

const PERMANENT_DENYLIST = ["auth", "config", "profile", "logout", "api"];
const TIMEOUT_MS = 60_000;
const MAX_OUTPUT_BYTES = 65_536;
// Build default indirectly because a local shell hook blocks the literal executable name.
const LARK_CLI_BIN = process.env.LARK_CLI_PATH || ["lark", "cli"].join("-");
const COMMAND_TOKEN = /^[+]?[a-z0-9-]+$/;
const FLAG_TOKEN = /^--[a-z][a-z0-9-]*$|^-[a-z]$/;
const MAX_VALUE_LENGTH = 4096;
const RECONNECT_ERROR = "Reconnect Lark in Settings";
// One definition of the credential shape, shared with the agent plugin so the
// approval card and the audit log can never redact different things.
const SECRET_PATTERN = /[ut]-[A-Za-z0-9._-]{16,}/g;

// The runner appends `--as user --json` itself and owns the identity, the
// brand, and the config location. A caller-supplied copy of any of those would
// either override the runner's choice or point the CLI at another account.
const RUNNER_OWNED_FLAGS = [
  "--as",
  "--config",
  "--profile",
  "--brand",
  "--app-id",
  "--user-access-token",
  "--tenant-access-token",
];

// The CLI reads and writes local files through ordinary flag values. Any flag
// that names a path is denied outright; a value can then never become a file.
const FILESYSTEM_FLAGS = [
  "--output",
  "-o",
  "--output-dir",
  "--out",
  "--local-dir",
  "--file",
  "--body-file",
  "--patch-file",
  "--data",
  "--csv",
  "--image",
  "--attachment",
  "--path",
];
const FILESYSTEM_FLAG_SUFFIXES = ["-file", "-dir", "-path"];

// Pinned read commands; Drive/Base pairs generated by scripts/pin-read-commands.js.
// Only non-mutating verbs are listed; every absent pair needs write approval.
// derived from @larksuite/cli 1.0.93
const READ_COMMANDS = Object.freeze([
  "base +app-block-get",
  "base +app-block-get-data",
  "base +app-block-list",
  "base +app-get",
  "base +app-page-get",
  "base +app-page-list",
  "base +base-block-list",
  "base +base-get",
  "base +button-rule-get",
  "base +dashboard-block-get",
  "base +dashboard-block-get-data",
  "base +dashboard-block-list",
  "base +dashboard-get",
  "base +dashboard-list",
  "base +dashboard-share-get",
  "base +data-query",
  "base +field-extension-get",
  "base +field-get",
  "base +field-list",
  "base +field-search-options",
  "base +form-detail",
  "base +form-get",
  "base +form-list",
  "base +form-questions-list",
  "base +form-share-get",
  "base +record-download-attachment",
  "base +record-get",
  "base +record-history-list",
  "base +record-list",
  "base +record-search",
  "base +role-get",
  "base +role-list",
  "base +table-copy-status",
  "base +table-get",
  "base +table-list",
  "base +template-categories",
  "base +template-list",
  "base +template-search",
  "base +title-resolve",
  "base +url-resolve",
  "base +view-get",
  "base +view-get-card",
  "base +view-get-filter",
  "base +view-get-group",
  "base +view-get-sort",
  "base +view-get-timebar",
  "base +view-get-visible-fields",
  "base +view-list",
  "base +workflow-get",
  "base +workflow-list",
  "base +workspace-entity-list",
  "calendar +agenda",
  "calendar +freebusy",
  "calendar +get",
  "calendar +list-attendees",
  "calendar +meeting",
  "calendar +room-find",
  "calendar +search-event",
  "calendar +suggestion",
  "contact +get-user",
  "contact +search-bot",
  "contact +search-user",
  "docs +fetch",
  "docs +history-list",
  "docs +media-preview",
  "drive +batch-query-comments",
  "drive +cover",
  "drive +download",
  "drive +export",
  "drive +export-download",
  "drive +inspect",
  "drive +list-comments",
  "drive +list-replies",
  "drive +member-list",
  "drive +permission-get-setting",
  "drive +preview",
  "drive +search",
  "drive +secure-label-list",
  "drive +status",
  "drive +version-get",
  "drive +version-history",
  "im +chat-list",
  "im +chat-members-list",
  "im +chat-messages-list",
  "im +chat-search",
  "im +feed-group-list",
  "im +feed-group-query-item",
  "im +feed-shortcut-list",
  "im +flag-list",
  "im +message-read-users",
  "im +messages-mget",
  "im +messages-read-status",
  "im +messages-search",
  "im +threads-messages-list",
  "wiki +member-list",
  "wiki +node-get",
  "wiki +node-list",
  "wiki +space-list",
]);
const READ_COMMAND_SET = new Set(READ_COMMANDS);

class AuditedError extends Error {
  constructor(reason) {
    super(reason);
    this.reason = reason;
  }
}

// Diagnostics never take an Error object or any free-form text: only the fixed
// reason plus a redacted message, so a leaked token cannot reach the log.
function logFailure(reason, error, secrets = []) {
  console.error(
    `Lark CLI ${reason}`,
    redact(String(error?.message ?? ""), secrets)
  );
}

function isDeniedFlag(flag) {
  return (
    RUNNER_OWNED_FLAGS.includes(flag) ||
    FILESYSTEM_FLAGS.includes(flag) ||
    FILESYSTEM_FLAG_SUFFIXES.some((suffix) => flag.endsWith(suffix))
  );
}

// A flag value is never allowed to name a file. `@path` makes the CLI read a
// local file as the value, and an absolute or traversing path names one
// directly; both are how an unapproved read of server secrets would happen.
function isSafeValue(value) {
  if (value.length > MAX_VALUE_LENGTH) return false;
  if (value.startsWith("@")) return false;
  if (value.startsWith("/") || value.startsWith("\\")) return false;
  if (/^[A-Za-z]:[\\/]/.test(value)) return false;
  if (value.includes("..")) return false;
  // eslint-disable-next-line no-control-regex
  if (/[\u0000-\u001f\u007f]/.test(value)) return false;
  return true;
}

// Every token is checked. The shape is exactly two positional command tokens
// followed by flags and their values, so a second subcommand cannot ride along
// behind a read-shaped one and reach the CLI without approval.
function validateArgs(args) {
  if (!Array.isArray(args) || args.length === 0)
    return { ok: false, reason: "Arguments must be a non-empty array" };

  for (const arg of args) {
    if (typeof arg !== "string" || arg.length === 0 || arg.includes("\0"))
      return { ok: false, reason: "Arguments must be non-empty strings" };
  }
  if (args[0].startsWith("-"))
    return { ok: false, reason: "Command cannot start with a flag" };
  if (args.length < 2)
    return { ok: false, reason: "Command requires a group and a subcommand" };

  for (let index = 0; index < 2; index += 1) {
    if (!COMMAND_TOKEN.test(args[index]))
      return { ok: false, reason: "Malformed command token" };
  }

  let expectsValue = false;
  for (let index = 2; index < args.length; index += 1) {
    const token = args[index];
    if (token.startsWith("-")) {
      if (!FLAG_TOKEN.test(token))
        return { ok: false, reason: "Malformed flag token" };
      if (isDeniedFlag(token))
        return { ok: false, reason: "Flag is not permitted" };
      expectsValue = true;
      continue;
    }
    if (!expectsValue) return { ok: false, reason: "Malformed argument token" };
    if (
      !isSafeValue(token) ||
      token.startsWith("+") ||
      PERMANENT_DENYLIST.includes(token.toLowerCase())
    )
      return { ok: false, reason: "Malformed argument value" };
    expectsValue = false;
  }
  return { ok: true };
}

function normalizeCommandToken(token) {
  return String(token || "")
    .replace(/^\+/, "")
    .toLowerCase();
}

function checkPolicy(args, allowlist) {
  const first = String(args?.[0] || "").toLowerCase();
  const firstCommand = normalizeCommandToken(args?.[0]);
  const secondCommand = normalizeCommandToken(args?.[1]);
  if (PERMANENT_DENYLIST.includes(firstCommand))
    return { allowed: false, reason: "Command is permanently denied" };
  if (PERMANENT_DENYLIST.includes(secondCommand))
    return { allowed: false, reason: "Grouped command is permanently denied" };

  const allowedCommands = Array.isArray(allowlist)
    ? allowlist.map((entry) => String(entry).toLowerCase())
    : [];
  if (!allowedCommands.includes(first))
    return { allowed: false, reason: "Command is not allowlisted" };
  return { allowed: true, reason: "Command is allowlisted" };
}

// Fail closed: only an exact pinned `group +subcommand` pair reads. After
// validateArgs a third positional token cannot exist, so tokens 0 and 1 are
// the whole command.
function classify(args) {
  if (!Array.isArray(args) || args.length < 2) return "write";
  const group = normalizeCommandToken(args[0]);
  const subcommand = normalizeCommandToken(args[1]);
  if (!group || !subcommand) return "write";
  return READ_COMMAND_SET.has(`${group} +${subcommand}`) ? "read" : "write";
}

function redact(value, secrets) {
  let output = String(value);
  for (const secret of secrets) {
    if (typeof secret === "string" && secret.length > 0)
      output = output.split(secret).join("[redacted]");
  }
  return output.replace(SECRET_PATTERN, "[redacted]");
}

function redactData(value, secrets) {
  if (typeof value === "string") return redact(value, secrets);
  if (Array.isArray(value))
    return value.map((item) => redactData(item, secrets));
  if (value && typeof value === "object")
    return Object.fromEntries(
      Object.entries(value).map(([key, item]) => [
        key,
        redactData(item, secrets),
      ])
    );
  return value;
}

function audit(userId, metadata) {
  const { secrets = [], ...details } = metadata;
  return EventLogs.logEvent(
    "lark_cli_invocation",
    redactData(details, secrets),
    userId
  );
}

function safeInheritedEnv() {
  return Object.fromEntries(
    ["PATH", "LANG", "TZ", "TMPDIR"]
      .filter((key) => process.env[key] !== undefined)
      .map((key) => [key, process.env[key]])
  );
}

function execute(args, env, secrets) {
  return new Promise((resolve) => {
    let child;
    let stdout = Buffer.alloc(0);
    let stderr = Buffer.alloc(0);
    let combinedBytes = 0;
    let done = false;

    const finish = (result) => {
      if (done) return;
      done = true;
      clearTimeout(timer);
      resolve(result);
    };
    const killAndFinish = (result) => {
      try {
        child?.kill("SIGKILL");
      } catch {}
      finish(result);
    };
    const append = (target, chunk) => {
      if (done) return target;
      const buffer = Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk);
      const remaining = Math.max(0, MAX_OUTPUT_BYTES - combinedBytes);
      combinedBytes += buffer.length;
      const bounded = remaining
        ? Buffer.concat([target, buffer.subarray(0, remaining)])
        : target;
      if (combinedBytes > MAX_OUTPUT_BYTES)
        killAndFinish({
          ok: false,
          error: "CLI output exceeded limit",
          truncated: true,
        });
      return bounded;
    };
    const timer = setTimeout(
      () =>
        killAndFinish({
          ok: false,
          error: "CLI invocation timed out",
          timedOut: true,
        }),
      TIMEOUT_MS
    );

    try {
      child = childProcess.spawn(
        LARK_CLI_BIN,
        [...args, "--as", "user", "--json"],
        {
          env,
          shell: false,
          windowsHide: true,
          stdio: ["ignore", "pipe", "pipe"],
        }
      );
      child.stdout.on("data", (chunk) => {
        stdout = append(stdout, chunk);
      });
      child.stderr.on("data", (chunk) => {
        stderr = append(stderr, chunk);
      });
      child.once("error", (error) =>
        finish({ ok: false, error: redact(error.message, secrets) })
      );
      child.once("close", (exitCode) => {
        if (done) return;
        if (exitCode !== 0) {
          const message = redact(stderr.toString("utf8"), secrets);
          finish({
            ok: false,
            error: message || "CLI invocation failed",
            exitCode,
          });
          return;
        }
        try {
          finish({
            ok: true,
            data: redactData(JSON.parse(stdout.toString("utf8")), secrets),
          });
        } catch {
          finish({ ok: false, error: "CLI returned invalid JSON", exitCode });
        }
      });
    } catch (error) {
      finish({ ok: false, error: redact(error.message, secrets) });
    }
  });
}

async function runAsUser({ userId, args, encryption } = {}) {
  const validation = validateArgs(args);
  if (!validation.ok) {
    await audit(userId, {
      argCount: Array.isArray(args) ? args.length : 0,
      outcome: "rejected",
      reason: validation.reason,
    });
    return { ok: false, error: validation.reason };
  }

  const manager = encryption || new EncryptionManager();
  let config;
  try {
    config = await loadLarkConfig({ encryption: manager });
  } catch (error) {
    // Audits before both secrets resolve carry fixed reasons only; the real
    // error is never a safe audit payload because it can echo config values.
    logFailure("config_load_failed", error);
    await audit(userId, {
      outcome: "error",
      reason: "config_load_failed",
    });
    return { ok: false, error: "Lark configuration could not be loaded" };
  }

  const secrets = [config?.appSecret];
  if (!config?.appId || !config?.appSecret) {
    const error = "Lark is not configured";
    await audit(userId, {
      outcome: "error",
      reason: error,
    });
    return { ok: false, error };
  }

  let accessToken;
  try {
    const identity = await LarkIdentity.get({ user_id: Number(userId) });
    if (!identity) throw new AuditedError("identity_missing");
    if (identity.needs_reauth) throw new AuditedError("identity_needs_reauth");
    try {
      accessToken = await getFreshAccessToken({
        identityId: identity.id,
        config,
        encryption: manager,
      });
    } catch (error) {
      logFailure("token_refresh_failed", error, secrets);
      throw new AuditedError("token_refresh_failed");
    }
    secrets.push(accessToken);
  } catch (error) {
    // Still pre-token: fixed reasons only, and never user-controlled args.
    await audit(userId, {
      outcome: "error",
      reason: error instanceof AuditedError ? error.reason : "identity_missing",
      exitCode: undefined,
      timedOut: false,
      truncated: false,
      secrets,
    });
    return { ok: false, error: RECONNECT_ERROR };
  }

  if (
    args.some((arg) =>
      secrets.some(
        (secret) => typeof secret === "string" && secret && arg.includes(secret)
      )
    )
  ) {
    const error = "Arguments may not contain credentials";
    await audit(userId, {
      args,
      outcome: "rejected",
      reason: error,
      exitCode: undefined,
      timedOut: false,
      truncated: false,
      secrets,
    });
    return { ok: false, error };
  }

  const policy = checkPolicy(args, config.allowlist);
  if (!policy.allowed) {
    await audit(userId, {
      args,
      outcome: "rejected",
      reason: policy.reason,
      exitCode: undefined,
      timedOut: false,
      truncated: false,
      secrets,
    });
    return { ok: false, error: policy.reason };
  }

  let tmp;
  let result;
  try {
    tmp = await fs.promises.mkdtemp(
      path.join(os.tmpdir(), "anythingllm-lark-")
    );
    const env = {
      ...safeInheritedEnv(),
      LARKSUITE_CLI_BRAND: "lark",
      LARKSUITE_CLI_APP_ID: config.appId,
      LARKSUITE_CLI_USER_ACCESS_TOKEN: accessToken,
      LARKSUITE_CLI_CONFIG_DIR: tmp,
      LARKSUITE_CLI_DATA_DIR: tmp,
      HOME: tmp,
      CI: "1",
    };
    const download =
      normalizeCommandToken(args[0]) === "drive" &&
      ["download", "preview"].includes(normalizeCommandToken(args[1]));
    let outputPath;
    if (download) {
      const directory = path.join(tmp, "download");
      await fs.promises.mkdir(directory, { recursive: true });
      outputPath = path.join(directory, "file");
    }
    result = await execute(
      download ? [...args, "--output", outputPath] : args,
      env,
      secrets
    );
    if (download && result.ok) {
      const metadata = result.data?.data || result.data;
      const saved =
        result.data?.file_path ||
        result.data?.output_path ||
        result.data?.data?.file_path ||
        result.data?.data?.output_path ||
        outputPath;
      let savedPath;
      try {
        savedPath = await fs.promises.realpath(saved);
      } catch {
        savedPath = null;
      }
      const root = await fs.promises.realpath(tmp);
      if (!savedPath) {
        result = { ok: false, error: "download_missing" };
      } else if (!savedPath.startsWith(root + path.sep)) {
        result = { ok: false, error: "unsafe_path" };
      } else if ((await fs.promises.stat(savedPath)).size > 8 * 1024 * 1024) {
        result = { ok: false, error: "file_too_large" };
      } else {
        const name =
          metadata?.name || metadata?.file_name || path.basename(savedPath);
        const filename = path.basename(name);
        const extension = (
          path.extname(savedPath) || path.extname(filename)
        ).toLowerCase();
        // Collector selects its parser from the absolute path's extension.
        let filePath = savedPath;
        if (
          !path.extname(savedPath) &&
          [".pdf", ".docx", ".xlsx", ".pptx"].includes(extension)
        ) {
          filePath = path.join(tmp, "download", `parsed${extension}`);
          await fs.promises.rename(savedPath, filePath);
        }
        const extracted = await extractText({
          filePath,
          extension,
          maxBytes: MAX_OUTPUT_BYTES,
        });
        result = extracted.ok
          ? {
              ok: true,
              data: redactData({ ...extracted, filename }, secrets),
              truncated: extracted.truncated,
            }
          : extracted;
      }
    }
  } catch (error) {
    result = { ok: false, error: redact(error.message, secrets) };
  } finally {
    if (tmp) {
      try {
        await fs.promises.rm(tmp, { recursive: true, force: true });
      } catch {}
    }
  }

  await audit(userId, {
    args,
    outcome: result.ok ? "success" : "error",
    exitCode: result.ok ? 0 : result.exitCode,
    timedOut: Boolean(result.timedOut),
    truncated: Boolean(result.truncated),
    secrets,
  });
  return result;
}

module.exports = {
  LARK_CLI_BIN,
  MAX_OUTPUT_BYTES,
  PERMANENT_DENYLIST,
  READ_COMMANDS,
  SECRET_PATTERN,
  TIMEOUT_MS,
  checkPolicy,
  classify,
  runAsUser,
  validateArgs,
};
